### ISSUE TITLE
Error in ipa and apk analysis

### ISSUE THREAD

**Issue by dukebarman** [wargio/fufluns#3]
I've tried to analysis the ipa and apk files and get an error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/fufluns/ios/ipa.py", line 56, in _ipa_analysis
    raise e
  File "/fufluns/ios/ipa.py", line 53, in _ipa_analysis
    mod.run_tests(ipa, r2, utils, r2help)
  File "/fufluns/ios/tests/bininfo.py", line 7, in run_tests
    o.binary.classes(filename, r2h.cmdj(r2, 'icj'))
  File "/fufluns/r2help.py", line 14, in cmdj
    return json.loads(v.replace('\\x', '\\u00'), strict=False)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 47 (char 46)
```

fufluns from master branch and was started in docker

**Comment by wargio** [comment]
I guess R2 JSON is broken.

**Comment by dukebarman** [comment]
I'm not sure that a same error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/fufluns/ios/ipa.py", line 56, in _ipa_analysis
    raise e
  File "/fufluns/ios/ipa.py", line 53, in _ipa_analysis
    mod.run_tests(ipa, r2, utils, r2help)
  File "/fufluns/ios/tests/plist.py", line 12, in run_tests
    plist = json.dumps(plist, indent=4)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Data is not JSON serializable
```

This error with another ipa file: https://github.com/OWASP/MSTG-Hacking-Playground/releases/download/1.0/MSTG-JWT.ipa

**Comment by dukebarman** [comment]
The first error in r2 libraries of mobile applications parsing:

```
r2 classes.dex
 -- Wait a minute! I found a bug, self-fixing ... OK
[0x00700000]> il
[Linked libraries]



1 library

[0x00700000]> ilj
["
  "]
[0x00700000]> q
[1]    24556 segmentation fault  r2 classes.dex
```

**Comment by wargio** [comment]
> The first error in r2 libraries of mobile applications parsing:
> 
> ```
> r2 classes.dex
>  -- Wait a minute! I found a bug, self-fixing ... OK
> [0x00700000]> il
> [Linked libraries]
> 
> 
> 
> 1 library
> 
> [0x00700000]> ilj
> ["
>   "]
> [0x00700000]> q
> [1]    24556 segmentation fault  r2 classes.dex
> ```
> 
> I've commented this line
> 
> https://github.com/wargio/fufluns/blob/5e372a77341d54d1fd032663cdc8f29234b875ef/android/tests/bininfo.py#L37
> and it works.

Please report this bug to r2. The data is badly encoded

**Comment by dukebarman** [comment]
Okay. And about IPA file:

It was another error:
https://github.com/wargio/fufluns/blob/5e372a77341d54d1fd032663cdc8f29234b875ef/ios/tests/bininfo.py#L7

Some encrypted names of methods have special chars.

**Comment by wargio** [comment]
i think is the same issue, which is bad encoding.

**Comment by wargio** [comment]
try to use the version i pushed on docker: https://hub.docker.com/r/deroad/fufluns/tags

**Comment by dukebarman** [comment]
Same errors

**Comment by wargio** [comment]
can you give me the binary over telegram?

**Comment by wargio** [comment]
Fixed android with https://github.com/wargio/fufluns/commit/2a4da2f9aa313e6edcbd31d85fc67982ec9630d3 and fixed iOS with https://github.com/wargio/fufluns/commit/4825793cbbaf0b92eb6a1f0f41695f98d7bf5299
